# Cross-compile https://github.com/fprime-community/fprime-zephyr-reference

name: "External Repo: Zephyr Reference (Pico 2)"

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'
# Cancel in-progress runs if a newer run is started on a given PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/')}}
jobs:
  get-branch:
    name: "Get target branch"
    uses: ./.github/workflows/reusable-get-pr-branch.yml
    with:
      target_repository: fprime-community/fprime-zephyr-reference

  build:
    name: "Zephyr Build"
    needs: get-branch
    uses: ./.github/workflows/reusable-project-ci.yml
    with:
        target_repository: fprime-community/fprime-zephyr-reference
        target_ref: ${{ needs.get-branch.outputs.target-branch }}
        ci_config_file: ./lib/fprime-zephyr/ci/sample-configs/pico2.yml

      
