# Builds and runs UTs on https://github.com/fprime-community/fprime-workshop-led-blinker

name: "External Repo: Tutorial: LedBlinker"

on:
  push:
    branches: [ devel, release/** ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'
# Cancel in-progress runs if a newer run is started on a given PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'devel') && !contains(github.ref, 'release/')}}

jobs:
  get-branch:
    name: "Get target branch"
    uses: ./.github/workflows/reusable-get-pr-branch.yml
    with:
      target_repository: fprime-community/fprime-workshop-led-blinker

  run:
    needs: get-branch
    name: ""
    uses: ./.github/workflows/reusable-project-builder.yml
    with: 
      target_repository: fprime-community/fprime-workshop-led-blinker
      fprime_location: lib/fprime
      build_location: LedBlinker
      run_unit_tests: true
      target_ref: ${{ needs.get-branch.outputs.target-branch }}
