# This workflow is intended for reuse by other workflows and will not run directly (no triggers).
# The behavior is to run the steps of fprime-ci.
name: "F´ CI - Reusable Workflow"

on:
  workflow_call:
    inputs:
      target_repository:
        description: "Additional external repository to checkout (<owner>/<repo>)"
        required: true
        type: string
      fprime_location:
        description: "Relative path from the external project root to its F´ submodule"
        required: false
        type: string
        default: "./lib/fprime"
      target_ref:
        description: "Branch on target to checkout"
        required: false
        type: string
        default: "devel"
      ci_config_file:
        required: true
        type: string
      run_unit_tests:
        description: "Run an additional job in parallel to run unit tests."
        required: false
        type: boolean
        default: true
      runs_on:
        description: "Platform to run on. Defaults to ubuntu-22.04"
        required: false
        type: string
        default: "ubuntu-22.04"
      runs_on_int:
        description: "Platform to run integration tests on. Defaults to: apple-ci"
        required: false
        type: string
        default: "apple-ci"
      runs_on_ut:
        description: "Platform to run UTs on. Defaults to ubuntu-22.04"
        required: false
        type: string
        default: "ubuntu-22.04"
jobs:
  build:
    runs-on: ${{ inputs.runs_on }}
    name: "Build"
    steps:
      - name: "Make Space"
        uses: nasa/fprime-actions/make-space@devel
      - name: "Set up target repository"
        uses: nasa/fprime-actions/external-repository-setup@devel
        with:
          target_repository: ${{ inputs.target_repository }}
          fprime_location: ${{ inputs.fprime_location }}
          target_ref: ${{ inputs.target_ref }}
          stage: build
      - name: "Build Binary"
        run: |
          CCACHE_DISABLE=1 fprime-ci -c ${{ inputs.ci_config_file }} --add-stage build
      - name: Archive Results
        uses: actions/upload-artifact@v4
        with:
          name: archive.tar.gz
          path: ./archive.tar.gz
  integration-tests:
    needs: build
    name: "Integration Tests"
    runs-on: ${{ inputs.runs_on_int }}
    steps:
      - name: "Set up target repository"
        uses: nasa/fprime-actions/external-repository-setup@devel
        with:
          target_repository: ${{ inputs.target_repository }}
          fprime_location: ${{ inputs.fprime_location }}
          target_ref: ${{ inputs.target_ref }}
          stage: int
      - name: Pull Archive Results
        uses: actions/download-artifact@v4
        with:
          name: archive.tar.gz
      - name: "Integration tests"
        run: |
            fprime-ci -c ${{ inputs.ci_config_file }} --skip-stage build
